### ISSUE TITLE
Encountering Pandas error when checking installation with simple benchmark

### ISSUE THREAD

**Issue by spresman** [ekernf01/perturbation_benchmarking#2]
Hi! Thanks for putting this together. I'm encountering the following error with both the minimal and full installation of the environments:

```
Traceback (most recent call last):
  File "/home/tea9yu/.conda/envs/ggrn/bin/pereggrn", line 33, in <module>
    sys.exit(load_entry_point('pereggrn', 'console_scripts', 'pereggrn')())
  File "/home/tea9yu/.conda/envs/ggrn/bin/pereggrn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/tea9yu/.conda/envs/ggrn/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/tea9yu/.conda/envs/ggrn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/sfs/gpfs/tardis/home/tea9yu/.conda/envs/ggrn/bin/do_one_experiment.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/sfs/gpfs/tardis/project/PlatigLab/users/sam/perturb_benchmark/pereggrn/do_one_experiment.py", line 238, in <module>
    evaluationPerPert, evaluationPerTarget = evaluator.evaluateCausalModel(
  File "/sfs/gpfs/tardis/project/PlatigLab/users/sam/perturb_benchmark/pereggrn/pereggrn/evaluator.py", line 448, in evaluateCausalModel
    evaluations[is_timescale_strict][prediction_timescale] = evaluateOnePrediction(
  File "/sfs/gpfs/tardis/project/PlatigLab/users/sam/perturb_benchmark/pereggrn/pereggrn/evaluator.py", line 891, in evaluateOnePrediction
    metrics = evaluate_across_perts(
  File "/sfs/gpfs/tardis/project/PlatigLab/users/sam/perturb_benchmark/pereggrn/pereggrn/evaluator.py", line 758, in evaluate_across_perts
    expression.obs.loc         [:, c].fillna(0) ==
  File "/home/tea9yu/.conda/envs/ggrn/lib/python3.9/site-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
  File "/home/tea9yu/.conda/envs/ggrn/lib/python3.9/site-packages/pandas/core/arraylike.py", line 40, in __eq__
    return self._cmp_method(other, operator.eq)
  File "/home/tea9yu/.conda/envs/ggrn/lib/python3.9/site-packages/pandas/core/series.py", line 6090, in _cmp_method
    raise ValueError("Can only compare identically-labeled Series objects")
ValueError: Can only compare identically-labeled Series objects
```
I followed the exact install without docker, and substituted the unzip command (issues with unzipping large files) for jar -xf. I've attached the complete stdout log and the pip dependencies for the ggrn environment. I appreciate it!

[log.txt](https://github.com/user-attachments/files/17508517/log.txt)
[pip_depp.txt](https://github.com/user-attachments/files/17508518/pip_depp.txt)

**Comment by ekernf01** [comment]
Thank you for trying out PEREGGRN! I am able to reproduce this exact issue, and it looks like I wrote this bug recently while adding features for a new timeseries modeling project that is still in stealth mode. I don't think this issue should affect the release of PEREGGRN accompanying our preprint. I will also try to get a fix out now.
